// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type LoginRequest struct {
	Username string `json:"userName"`
	Password string `json:"password"`
}

type LoginResponse struct {
	Token string `json:"token"`
}

type OpenLoginInfoResponse struct {
	Name string `json:"name"`
	Icon string `json:"icon"`
	Href string `json:"href"` // 跳转的地址
}

type OpenLoginRequest struct {
	Code string `json:"code"`
	Flag string `json:"flag"` // 登录标志
}
